name: Build Kivy App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1.2.0 # Ou use outra action atualizada como akaihola/kivy-buildozer-action
      with:
        command: buildozer android debug
        subpath: '.'
